INDIAN_STATES = {
    'Andhra Pradesh': ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna', 'Kurnool', 'Nellore', 'Prakasam', 'Srikakulam', 'Visakhapatnam', 'Vizianagaram', 'West Godavari', 'YSR Kadapa'],
    'Arunachal Pradesh': ['Tawang', 'West Kameng', 'East Kameng', 'Papum Pare', 'Kurung Kumey', 'Kra Daadi', 'Lower Subansiri', 'Upper Subansiri', 'West Siang', 'East Siang', 'Siang', 'Upper Siang', 'Lower Siang', 'Lower Dibang Valley', 'Dibang Valley', 'Anjaw', 'Lohit', 'Namsai', 'Changlang', 'Tirap', 'Longding'],
    'Assam': ['Baksa', 'Barpeta', 'Biswanath', 'Bongaigaon', 'Cachar', 'Charaideo', 'Chirang', 'Darrang', 'Dhemaji', 'Dhubri', 'Dibrugarh', 'Goalpara', 'Golaghat', 'Hailakandi', 'Hojai', 'Jorhat', 'Kamrup', 'Kamrup Metropolitan', 'Karbi Anglong', 'Karimganj', 'Kokrajhar', 'Lakhimpur', 'Majuli', 'Morigaon', 'Nagaon', 'Nalbari', 'Dima Hasao', 'Sivasagar', 'Sonitpur', 'South Salmara-Mankachar', 'Tinsukia', 'Udalguri', 'West Karbi Anglong'],
    'Bihar': ['Araria', 'Arwal', 'Aurangabad', 'Banka', 'Begusarai', 'Bhagalpur', 'Bhojpur', 'Buxar', 'Darbhanga', 'East Champaran', 'Gaya', 'Gopalganj', 'Jamui', 'Jehanabad', 'Kaimur', 'Katihar', 'Khagaria', 'Kishanganj', 'Lakhisarai', 'Madhepura', 'Madhubani', 'Munger', 'Muzaffarpur', 'Nalanda', 'Nawada', 'Patna', 'Purnia', 'Rohtas', 'Saharsa', 'Samastipur', 'Saran', 'Sheikhpura', 'Sheohar', 'Sitamarhi', 'Siwan', 'Supaul', 'Vaishali', 'West Champaran'],
    'Chhattisgarh': ['Balod', 'Baloda Bazar', 'Balrampur', 'Bastar', 'Bemetara', 'Bijapur', 'Bilaspur', 'Dantewada', 'Dhamtari', 'Durg', 'Gariaband', 'Gaurela-Pendra-Marwahi', 'Janjgir-Champa', 'Jashpur', 'Kabirdham', 'Kanker', 'Kondagaon', 'Korba', 'Koriya', 'Mahasamund', 'Mungeli', 'Narayanpur', 'Raigarh', 'Raipur', 'Rajnandgaon', 'Sukma', 'Surajpur', 'Surguja'],
    'Goa': ['North Goa', 'South Goa'],
    'Gujarat': ['Ahmedabad', 'Amreli', 'Anand', 'Aravalli', 'Banaskantha', 'Bharuch', 'Bhavnagar', 'Botad', 'Chhota Udaipur', 'Dahod', 'Dang', 'Devbhoomi Dwarka', 'Gandhinagar', 'Gir Somnath', 'Jamnagar', 'Junagadh', 'Kheda', 'Kutch', 'Mahisagar', 'Mehsana', 'Morbi', 'Narmada', 'Navsari', 'Panchmahal', 'Patan', 'Porbandar', 'Rajkot', 'Sabarkantha', 'Surat', 'Surendranagar', 'Tapi', 'Vadodara', 'Valsad'],
    'Haryana': ['Ambala', 'Bhiwani', 'Charkhi Dadri', 'Faridabad', 'Fatehabad', 'Gurugram', 'Hisar', 'Jhajjar', 'Jind', 'Kaithal', 'Karnal', 'Kurukshetra', 'Mahendragarh', 'Nuh', 'Palwal', 'Panchkula', 'Panipat', 'Rewari', 'Rohtak', 'Sirsa', 'Sonipat', 'Yamunanagar'],
    'Himachal Pradesh': ['Bilaspur', 'Chamba', 'Hamirpur', 'Kangra', 'Kinnaur', 'Kullu', 'Lahaul and Spiti', 'Mandi', 'Shimla', 'Sirmaur', 'Solan', 'Una'],
    'Jharkhand': ['Bokaro', 'Chatra', 'Deoghar', 'Dhanbad', 'Dumka', 'East Singhbhum', 'Garhwa', 'Giridih', 'Godda', 'Gumla', 'Hazaribagh', 'Jamtara', 'Khunti', 'Koderma', 'Latehar', 'Lohardaga', 'Pakur', 'Palamu', 'Ramgarh', 'Ranchi', 'Sahebganj', 'Seraikela Kharsawan', 'Simdega', 'West Singhbhum'],
    'Karnataka': ['Bagalkot', 'Ballari', 'Belagavi', 'Bengaluru Rural', 'Bengaluru Urban', 'Bidar', 'Chamarajanagar', 'Chikballapur', 'Chikkamagaluru', 'Chitradurga', 'Dakshina Kannada', 'Davangere', 'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kalaburagi', 'Kodagu', 'Kolar', 'Koppal', 'Mandya', 'Mysuru', 'Raichur', 'Ramanagara', 'Shivamogga', 'Tumakuru', 'Udupi', 'Uttara Kannada', 'Vijayapura', 'Yadgir'],
    'Kerala': ['Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'],
    'Madhya Pradesh': ['Agar Malwa', 'Alirajpur', 'Anuppur', 'Ashoknagar', 'Balaghat', 'Barwani', 'Betul', 'Bhind', 'Bhopal', 'Burhanpur', 'Chhatarpur', 'Chhindwara', 'Damoh', 'Datia', 'Dewas', 'Dhar', 'Dindori', 'Guna', 'Gwalior', 'Harda', 'Hoshangabad', 'Indore', 'Jabalpur', 'Jhabua', 'Katni', 'Khandwa', 'Khargone', 'Mandla', 'Mandsaur', 'Morena', 'Narsinghpur', 'Neemuch', 'Niwari', 'Panna', 'Raisen', 'Rajgarh', 'Ratlam', 'Rewa', 'Sagar', 'Satna', 'Sehore', 'Seoni', 'Shahdol', 'Shajapur', 'Sheopur', 'Shivpuri', 'Sidhi', 'Singrauli', 'Tikamgarh', 'Ujjain', 'Umaria', 'Vidisha'],
    'Maharashtra': ['Ahmednagar', 'Akola', 'Amravati', 'Chhatrapati Sambhajinagar', 'Beed', 'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nanded', 'Nandurbar', 'Nashik', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur', 'Thane', 'Wardha', 'Washim', 'Yavatmal'],
    'Manipur': ['Bishnupur', 'Chandel', 'Churachandpur', 'Imphal East', 'Imphal West', 'Jiribam', 'Kakching', 'Kamjong', 'Kangpokpi', 'Noney', 'Pherzawl', 'Senapati', 'Tamenglong', 'Tengnoupal', 'Thoubal', 'Ukhrul'],
    'Meghalaya': ['East Garo Hills', 'East Jaintia Hills', 'East Khasi Hills', 'North Garo Hills', 'Ri Bhoi', 'South Garo Hills', 'South West Garo Hills', 'South West Khasi Hills', 'West Garo Hills', 'West Jaintia Hills', 'West Khasi Hills'],
    'Mizoram': ['Aizawl', 'Champhai', 'Kolasib', 'Lawngtlai', 'Lunglei', 'Mamit', 'Saiha', 'Serchhip', 'Hnahthial', 'Khawzawl', 'Saitual'],
    'Nagaland': ['Dimapur', 'Kiphire', 'Kohima', 'Longleng', 'Mokokchung', 'Mon', 'Peren', 'Phek', 'Tuensang', 'Wokha', 'Zunheboto', 'Noklak', 'Tseminyu', 'Chumoukedima', 'Niuland', 'Shamator'],
    'Odisha': ['Angul', 'Balangir', 'Balasore', 'Bargarh', 'Bhadrak', 'Boudh', 'Cuttack', 'Deogarh', 'Dhenkanal', 'Gajapati', 'Ganjam', 'Jagatsinghpur', 'Jajpur', 'Jharsuguda', 'Kalahandi', 'Kandhamal', 'Kendrapara', 'Kendujhar', 'Khordha', 'Koraput', 'Malkangiri', 'Mayurbhanj', 'Nabarangpur', 'Nayagarh', 'Nuapada', 'Puri', 'Rayagada', 'Sambalpur', 'Sonepur', 'Sundargarh'],
    'Punjab': ['Amritsar', 'Barnala', 'Bathinda', 'Faridkot', 'Fatehgarh Sahib', 'Fazilka', 'Ferozepur', 'Gurdaspur', 'Hoshiarpur', 'Jalandhar', 'Kapurthala', 'Ludhiana', 'Mansa', 'Moga', 'Muktsar', 'Nawanshahr', 'Pathankot', 'Patiala', 'Rupnagar', 'Sangrur', 'SAS Nagar', 'Tarn Taran'],
    'Rajasthan': ['Ajmer', 'Alwar', 'Banswara', 'Baran', 'Barmer', 'Bharatpur', 'Bhilwara', 'Bikaner', 'Bundi', 'Chittorgarh', 'Churu', 'Dausa', 'Dholpur', 'Dungarpur', 'Hanumangarh', 'Jaipur', 'Jaisalmer', 'Jalore', 'Jhalawar', 'Jhunjhunu', 'Jodhpur', 'Karauli', 'Kota', 'Nagaur', 'Pali', 'Pratapgarh', 'Rajsamand', 'Sawai Madhopur', 'Sikar', 'Sirohi', 'Sri Ganganagar', 'Tonk', 'Udaipur'],
    'Sikkim': ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim', 'Pakyong', 'Soreng', 'Namchi', 'Gyalshing', 'Mangan', 'Gangtok'],
    'Tamil Nadu': ['Ariyalur', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri', 'Dindigul', 'Erode', 'Kanchipuram', 'Kanyakumari', 'Karur', 'Krishnagiri', 'Madurai', 'Nagapattinam', 'Namakkal', 'Nilgiris', 'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Salem', 'Sivaganga', 'Thanjavur', 'Theni', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore', 'Viluppuram', 'Virudhunagar'],
    'Telangana': ['Adilabad', 'Bhadradri Kothagudem', 'Hyderabad', 'Jagtial', 'Jangaon', 'Jayashankar Bhupalpally', 'Jogulamba Gadwal', 'Kamareddy', 'Karimnagar', 'Khammam', 'Komaram Bheem', 'Mahabubabad', 'Mahabubnagar', 'Mancherial', 'Medak', 'Medchal', 'Mulugu', 'Nagarkurnool', 'Nalgonda', 'Narayanpet', 'Nirmal', 'Nizamabad', 'Peddapalli', 'Rajanna Sircilla', 'Ranga Reddy', 'Sangareddy', 'Siddipet', 'Suryapet', 'Vikarabad', 'Wanaparthy', 'Warangal Rural', 'Warangal Urban', 'Yadadri Bhuvanagiri'],
    'Tripura': ['Dhalai', 'Gomati', 'Khowai', 'North Tripura', 'Sepahijala', 'South Tripura', 'Unakoti', 'West Tripura'],
    'Uttar Pradesh': ['Agra', 'Aligarh', 'Ambedkar Nagar', 'Amethi', 'Amroha', 'Auraiya', 'Azamgarh', 'Baghpat', 'Bahraich', 'Ballia', 'Balrampur', 'Banda', 'Barabanki', 'Bareilly', 'Basti', 'Bhadohi', 'Bijnor', 'Budaun', 'Bulandshahr', 'Chandauli', 'Chitrakoot', 'Deoria', 'Etah', 'Etawah', 'Ayodhya', 'Farrukhabad', 'Fatehpur', 'Firozabad', 'Gautam Buddha Nagar', 'Ghaziabad', 'Ghazipur', 'Gonda', 'Gorakhpur', 'Hamirpur', 'Hapur', 'Hardoi', 'Hathras', 'Jalaun', 'Jaunpur', 'Jhansi', 'Kannauj', 'Kanpur Dehat', 'Kanpur Nagar', 'Kasganj', 'Kaushambi', 'Kushinagar', 'Lakhimpur Kheri', 'Lalitpur', 'Lucknow', 'Maharajganj', 'Mahoba', 'Mainpuri', 'Mathura', 'Mau', 'Meerut', 'Mirzapur', 'Moradabad', 'Muzaffarnagar', 'Pilibhit', 'Pratapgarh', 'Prayagraj', 'Rae Bareli', 'Rampur', 'Saharanpur', 'Sambhal', 'Sant Kabir Nagar', 'Shahjahanpur', 'Shamli', 'Shravasti', 'Siddharthnagar', 'Sitapur', 'Sonbhadra', 'Sultanpur', 'Unnao', 'Varanasi'],
    'Uttarakhand': ['Almora', 'Bageshwar', 'Chamoli', 'Champawat', 'Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag', 'Tehri Garhwal', 'Udham Singh Nagar', 'Uttarkashi'],
    'West Bengal': ['Alipurduar', 'Bankura', 'Birbhum', 'Cooch Behar', 'Dakshin Dinajpur', 'Darjeeling', 'Hooghly', 'Howrah', 'Jalpaiguri', 'Jhargram', 'Kalimpong', 'Kolkata', 'Malda', 'Murshidabad', 'Nadia', 'North 24 Parganas', 'Paschim Bardhaman', 'Paschim Medinipur', 'Purba Bardhaman', 'Purba Medinipur', 'Purulia', 'South 24 Parganas', 'Uttar Dinajpur']
}

SOIL_TYPES = {
    'Andhra Pradesh': {
        'Anantapur': 'Red Sandy Loam',
        'Chittoor': 'Red Loam',
        'East Godavari': 'Alluvial',
        'Guntur': 'Black Cotton',
        'Krishna': 'Alluvial',
        'Kurnool': 'Red Sandy Loam',
        'Nellore': 'Coastal Alluvial',
        'Prakasam': 'Red Sandy Loam',
        'Srikakulam': 'Coastal Alluvial',
        'Visakhapatnam': 'Red Loam',
        'Vizianagaram': 'Red Loam',
        'West Godavari': 'Alluvial',
        'YSR Kadapa': 'Red Sandy Loam'
    },
    'Karnataka': {
        'Bagalkot': 'Black Cotton',
        'Ballari': 'Red Sandy Loam',
        'Belagavi': 'Black Cotton',
        'Bengaluru Rural': 'Red Loam',
        'Bengaluru Urban': 'Red Loam',
        'Bidar': 'Black Cotton',
        'Chamarajanagar': 'Red Loam',
        'Chikballapur': 'Red Loam',
        'Chikkamagaluru': 'Red Loam',
        'Chitradurga': 'Red Sandy Loam',
        'Dakshina Kannada': 'Laterite',
        'Davanagere': 'Red Sandy Loam',
        'Dharwad': 'Black Cotton',
        'Gadag': 'Black Cotton',
        'Hassan': 'Red Loam',
        'Haveri': 'Black Cotton',
        'Kalaburagi': 'Black Cotton',
        'Kodagu': 'Laterite',
        'Kolar': 'Red Loam',
        'Koppal': 'Black Cotton',
        'Mandya': 'Red Loam',
        'Mysuru': 'Red Loam',
        'Raichur': 'Black Cotton',
        'Ramanagara': 'Red Loam',
        'Shivamogga': 'Red Loam',
        'Tumakuru': 'Red Sandy Loam',
        'Udupi': 'Laterite',
        'Uttara Kannada': 'Laterite',
        'Vijayapura': 'Black Cotton',
        'Yadgir': 'Black Cotton'
    },
    'Maharashtra': {
        'Pune': 'Black Cotton',
        'Mumbai City': 'Coastal Alluvial',
        'Mumbai Suburban': 'Coastal Alluvial',
        'Nagpur': 'Black Cotton',
        'Nashik': 'Black Cotton',
        'Thane': 'Coastal Alluvial',
        'Aurangabad': 'Black Cotton',
        'Solapur': 'Black Cotton',
        'Kolhapur': 'Black Cotton',
        'Amravati': 'Black Cotton',
        'Sangli': 'Black Cotton',
        'Ahmednagar': 'Black Cotton',
        'Jalgaon': 'Black Cotton',
        'Akola': 'Black Cotton',
        'Latur': 'Black Cotton',
        'Satara': 'Black Cotton',
        'Ratnagiri': 'Coastal Alluvial',
        'Raigad': 'Coastal Alluvial',
        'Parbhani': 'Black Cotton',
        'Nanded': 'Black Cotton',
        'Beed': 'Black Cotton',
        'Osmanabad': 'Black Cotton',
        'Jalna': 'Black Cotton',
        'Buldhana': 'Black Cotton',
        'Wardha': 'Black Cotton',
        'Yavatmal': 'Black Cotton',
        'Chandrapur': 'Black Cotton',
        'Gondia': 'Black Cotton',
        'Bhandara': 'Black Cotton',
        'Gadchiroli': 'Red Loam',
        'Washim': 'Black Cotton',
        'Hingoli': 'Black Cotton',
        'Nandurbar': 'Black Cotton',
        'Dhule': 'Black Cotton',
        'Palghar': 'Coastal Alluvial'
    },
    'Punjab': {
        'Amritsar': 'Alluvial',
        'Barnala': 'Alluvial',
        'Bathinda': 'Alluvial',
        'Faridkot': 'Alluvial',
        'Fatehgarh Sahib': 'Alluvial',
        'Fazilka': 'Alluvial',
        'Ferozepur': 'Alluvial',
        'Gurdaspur': 'Alluvial',
        'Hoshiarpur': 'Alluvial',
        'Jalandhar': 'Alluvial',
        'Kapurthala': 'Alluvial',
        'Ludhiana': 'Alluvial',
        'Mansa': 'Alluvial',
        'Moga': 'Alluvial',
        'Muktsar': 'Alluvial',
        'Nawanshahr': 'Alluvial',
        'Pathankot': 'Alluvial',
        'Patiala': 'Alluvial',
        'Rupnagar': 'Alluvial',
        'Sangrur': 'Alluvial',
        'SAS Nagar': 'Alluvial',
        'Tarn Taran': 'Alluvial'
    },
    'Haryana': {
        'Ambala': 'Alluvial',
        'Bhiwani': 'Alluvial',
        'Charkhi Dadri': 'Alluvial',
        'Faridabad': 'Alluvial',
        'Fatehabad': 'Alluvial',
        'Gurugram': 'Alluvial',
        'Hisar': 'Alluvial',
        'Jhajjar': 'Alluvial',
        'Jind': 'Alluvial',
        'Kaithal': 'Alluvial',
        'Karnal': 'Alluvial',
        'Kurukshetra': 'Alluvial',
        'Mahendragarh': 'Alluvial',
        'Nuh': 'Alluvial',
        'Palwal': 'Alluvial',
        'Panchkula': 'Alluvial',
        'Panipat': 'Alluvial',
        'Rewari': 'Alluvial',
        'Rohtak': 'Alluvial',
        'Sirsa': 'Alluvial',
        'Sonipat': 'Alluvial',
        'Yamunanagar': 'Alluvial'
    },
    'Uttar Pradesh': {
        'Agra': 'Alluvial',
        'Aligarh': 'Alluvial',
        'Ambedkar Nagar': 'Alluvial',
        'Amethi': 'Alluvial',
        'Amroha': 'Alluvial',
        'Auraiya': 'Alluvial',
        'Azamgarh': 'Alluvial',
        'Baghpat': 'Alluvial',
        'Bahraich': 'Alluvial',
        'Ballia': 'Alluvial',
        'Balrampur': 'Alluvial',
        'Banda': 'Alluvial',
        'Barabanki': 'Alluvial',
        'Bareilly': 'Alluvial',
        'Basti': 'Alluvial',
        'Bhadohi': 'Alluvial',
        'Bijnor': 'Alluvial',
        'Budaun': 'Alluvial',
        'Bulandshahr': 'Alluvial',
        'Chandauli': 'Alluvial',
        'Chitrakoot': 'Alluvial',
        'Deoria': 'Alluvial',
        'Etah': 'Alluvial',
        'Etawah': 'Alluvial',
        'Ayodhya': 'Alluvial',
        'Farrukhabad': 'Alluvial',
        'Fatehpur': 'Alluvial',
        'Firozabad': 'Alluvial',
        'Gautam Buddha Nagar': 'Alluvial',
        'Ghaziabad': 'Alluvial',
        'Ghazipur': 'Alluvial',
        'Gonda': 'Alluvial',
        'Gorakhpur': 'Alluvial',
        'Hamirpur': 'Alluvial',
        'Hapur': 'Alluvial',
        'Hardoi': 'Alluvial',
        'Hathras': 'Alluvial',
        'Jalaun': 'Alluvial',
        'Jaunpur': 'Alluvial',
        'Jhansi': 'Alluvial',
        'Kannauj': 'Alluvial',
        'Kanpur Dehat': 'Alluvial',
        'Kanpur Nagar': 'Alluvial',
        'Kasganj': 'Alluvial',
        'Kaushambi': 'Alluvial',
        'Kushinagar': 'Alluvial',
        'Lakhimpur Kheri': 'Alluvial',
        'Lalitpur': 'Alluvial',
        'Lucknow': 'Alluvial',
        'Maharajganj': 'Alluvial',
        'Mahoba': 'Alluvial',
        'Mainpuri': 'Alluvial',
        'Mathura': 'Alluvial',
        'Mau': 'Alluvial',
        'Meerut': 'Alluvial',
        'Mirzapur': 'Alluvial',
        'Moradabad': 'Alluvial',
        'Muzaffarnagar': 'Alluvial',
        'Pilibhit': 'Alluvial',
        'Pratapgarh': 'Alluvial',
        'Prayagraj': 'Alluvial',
        'Rae Bareli': 'Alluvial',
        'Rampur': 'Alluvial',
        'Saharanpur': 'Alluvial',
        'Sambhal': 'Alluvial',
        'Sant Kabir Nagar': 'Alluvial',
        'Shahjahanpur': 'Alluvial',
        'Shamli': 'Alluvial',
        'Shravasti': 'Alluvial',
        'Siddharthnagar': 'Alluvial',
        'Sitapur': 'Alluvial',
        'Sonbhadra': 'Alluvial',
        'Sultanpur': 'Alluvial',
        'Unnao': 'Alluvial',
        'Varanasi': 'Alluvial'
    },
    'Rajasthan': {
        'Ajmer': 'Red Sandy Loam',
        'Alwar': 'Red Sandy Loam',
        'Banswara': 'Black Cotton',
        'Baran': 'Black Cotton',
        'Barmer': 'Red Sandy Loam',
        'Bharatpur': 'Alluvial',
        'Bhilwara': 'Red Sandy Loam',
        'Bikaner': 'Red Sandy Loam',
        'Bundi': 'Black Cotton',
        'Chittorgarh': 'Black Cotton',
        'Churu': 'Red Sandy Loam',
        'Dausa': 'Red Sandy Loam',
        'Dholpur': 'Red Sandy Loam',
        'Dungarpur': 'Black Cotton',
        'Hanumangarh': 'Alluvial',
        'Jaipur': 'Red Sandy Loam',
        'Jaisalmer': 'Red Sandy Loam',
        'Jalore': 'Red Sandy Loam',
        'Jhalawar': 'Black Cotton',
        'Jhunjhunu': 'Red Sandy Loam',
        'Jodhpur': 'Red Sandy Loam',
        'Karauli': 'Red Sandy Loam',
        'Kota': 'Black Cotton',
        'Nagaur': 'Red Sandy Loam',
        'Pali': 'Red Sandy Loam',
        'Pratapgarh': 'Black Cotton',
        'Rajsamand': 'Black Cotton',
        'Sawai Madhopur': 'Red Sandy Loam',
        'Sikar': 'Red Sandy Loam',
        'Sirohi': 'Red Sandy Loam',
        'Sri Ganganagar': 'Alluvial',
        'Tonk': 'Red Sandy Loam',
        'Udaipur': 'Black Cotton'
    },
    'Gujarat': {
        'Ahmedabad': 'Black Cotton',
        'Amreli': 'Black Cotton',
        'Anand': 'Black Cotton',
        'Aravalli': 'Black Cotton',
        'Banaskantha': 'Black Cotton',
        'Bharuch': 'Black Cotton',
        'Bhavnagar': 'Black Cotton',
        'Botad': 'Black Cotton',
        'Chhota Udaipur': 'Black Cotton',
        'Dahod': 'Black Cotton',
        'Dang': 'Laterite',
        'Devbhoomi Dwarka': 'Coastal Alluvial',
        'Gandhinagar': 'Black Cotton',
        'Gir Somnath': 'Black Cotton',
        'Jamnagar': 'Black Cotton',
        'Junagadh': 'Black Cotton',
        'Kheda': 'Black Cotton',
        'Kutch': 'Black Cotton',
        'Mahisagar': 'Black Cotton',
        'Mehsana': 'Black Cotton',
        'Morbi': 'Black Cotton',
        'Narmada': 'Black Cotton',
        'Navsari': 'Black Cotton',
        'Panchmahal': 'Black Cotton',
        'Patan': 'Black Cotton',
        'Porbandar': 'Coastal Alluvial',
        'Rajkot': 'Black Cotton',
        'Sabarkantha': 'Black Cotton',
        'Surat': 'Black Cotton',
        'Surendranagar': 'Black Cotton',
        'Tapi': 'Black Cotton',
        'Vadodara': 'Black Cotton',
        'Valsad': 'Black Cotton'
    },
    'Tamil Nadu': {
        'Ariyalur': 'Red Loam',
        'Chennai': 'Coastal Alluvial',
        'Coimbatore': 'Red Loam',
        'Cuddalore': 'Coastal Alluvial',
        'Dharmapuri': 'Red Loam',
        'Dindigul': 'Red Loam',
        'Erode': 'Red Loam',
        'Kanchipuram': 'Red Loam',
        'Kanyakumari': 'Laterite',
        'Karur': 'Red Loam',
        'Krishnagiri': 'Red Loam',
        'Madurai': 'Red Loam',
        'Nagapattinam': 'Coastal Alluvial',
        'Namakkal': 'Red Loam',
        'Nilgiris': 'Laterite',
        'Perambalur': 'Red Loam',
        'Pudukkottai': 'Red Loam',
        'Ramanathapuram': 'Red Loam',
        'Salem': 'Red Loam',
        'Sivaganga': 'Red Loam',
        'Thanjavur': 'Alluvial',
        'Theni': 'Red Loam',
        'Thoothukudi': 'Coastal Alluvial',
        'Tiruchirappalli': 'Red Loam',
        'Tirunelveli': 'Red Loam',
        'Tiruppur': 'Red Loam',
        'Tiruvallur': 'Red Loam',
        'Tiruvannamalai': 'Red Loam',
        'Tiruvarur': 'Alluvial',
        'Vellore': 'Red Loam',
        'Viluppuram': 'Red Loam',
        'Virudhunagar': 'Red Loam'
    },
    'Kerala': {
        'Alappuzha': 'Laterite',
        'Ernakulam': 'Laterite',
        'Idukki': 'Laterite',
        'Kannur': 'Laterite',
        'Kasaragod': 'Laterite',
        'Kollam': 'Laterite',
        'Kottayam': 'Laterite',
        'Kozhikode': 'Laterite',
        'Malappuram': 'Laterite',
        'Palakkad': 'Laterite',
        'Pathanamthitta': 'Laterite',
        'Thiruvananthapuram': 'Laterite',
        'Thrissur': 'Laterite',
        'Wayanad': 'Laterite'
    }
}

CLIMATE_ZONES = {
    'Andhra Pradesh': {
        'Anantapur': 'Semi-Arid',
        'Chittoor': 'Semi-Arid',
        'East Godavari': 'Tropical Wet',
        'Guntur': 'Tropical Wet and Dry',
        'Krishna': 'Tropical Wet',
        'Kurnool': 'Semi-Arid',
        'Nellore': 'Tropical Wet',
        'Prakasam': 'Semi-Arid',
        'Srikakulam': 'Tropical Wet',
        'Visakhapatnam': 'Tropical Wet',
        'Vizianagaram': 'Tropical Wet',
        'West Godavari': 'Tropical Wet',
        'YSR Kadapa': 'Semi-Arid'
    },
    'Karnataka': {
        'Bagalkot': 'Semi-Arid',
        'Ballari': 'Semi-Arid',
        'Belagavi': 'Tropical Wet and Dry',
        'Bengaluru Rural': 'Tropical Wet and Dry',
        'Bengaluru Urban': 'Tropical Wet and Dry',
        'Bidar': 'Semi-Arid',
        'Chamarajanagar': 'Tropical Wet and Dry',
        'Chikballapur': 'Tropical Wet and Dry',
        'Chikkamagaluru': 'Tropical Wet and Dry',
        'Chitradurga': 'Semi-Arid',
        'Dakshina Kannada': 'Tropical Wet',
        'Davanagere': 'Semi-Arid',
        'Dharwad': 'Tropical Wet and Dry',
        'Gadag': 'Semi-Arid',
        'Hassan': 'Tropical Wet and Dry',
        'Haveri': 'Tropical Wet and Dry',
        'Kalaburagi': 'Semi-Arid',
        'Kodagu': 'Tropical Wet',
        'Kolar': 'Tropical Wet and Dry',
        'Koppal': 'Semi-Arid',
        'Mandya': 'Tropical Wet and Dry',
        'Mysuru': 'Tropical Wet and Dry',
        'Raichur': 'Semi-Arid',
        'Ramanagara': 'Tropical Wet and Dry',
        'Shivamogga': 'Tropical Wet',
        'Tumakuru': 'Tropical Wet and Dry',
        'Udupi': 'Tropical Wet',
        'Uttara Kannada': 'Tropical Wet',
        'Vijayapura': 'Semi-Arid',
        'Yadgir': 'Semi-Arid'
    },
    'Maharashtra': {
        'Pune': 'Tropical Wet and Dry',
        'Mumbai City': 'Tropical Wet',
        'Mumbai Suburban': 'Tropical Wet',
        'Nagpur': 'Tropical Wet and Dry',
        'Nashik': 'Tropical Wet and Dry',
        'Thane': 'Tropical Wet',
        'Aurangabad': 'Semi-Arid',
        'Solapur': 'Semi-Arid',
        'Kolhapur': 'Tropical Wet',
        'Amravati': 'Tropical Wet and Dry',
        'Sangli': 'Tropical Wet and Dry',
        'Ahmednagar': 'Tropical Wet and Dry',
        'Jalgaon': 'Semi-Arid',
        'Akola': 'Tropical Wet and Dry',
        'Latur': 'Semi-Arid',
        'Satara': 'Tropical Wet and Dry',
        'Ratnagiri': 'Tropical Wet',
        'Raigad': 'Tropical Wet',
        'Parbhani': 'Semi-Arid',
        'Nanded': 'Semi-Arid',
        'Beed': 'Semi-Arid',
        'Osmanabad': 'Semi-Arid',
        'Jalna': 'Semi-Arid',
        'Buldhana': 'Tropical Wet and Dry',
        'Wardha': 'Tropical Wet and Dry',
        'Yavatmal': 'Tropical Wet and Dry',
        'Chandrapur': 'Tropical Wet and Dry',
        'Gondia': 'Tropical Wet and Dry',
        'Bhandara': 'Tropical Wet and Dry',
        'Gadchiroli': 'Tropical Wet',
        'Washim': 'Tropical Wet and Dry',
        'Hingoli': 'Semi-Arid',
        'Nandurbar': 'Tropical Wet',
        'Dhule': 'Semi-Arid',
        'Palghar': 'Tropical Wet'
    },
    'Punjab': {
        'Amritsar': 'Semi-Arid',
        'Barnala': 'Semi-Arid',
        'Bathinda': 'Semi-Arid',
        'Faridkot': 'Semi-Arid',
        'Fatehgarh Sahib': 'Semi-Arid',
        'Fazilka': 'Semi-Arid',
        'Ferozepur': 'Semi-Arid',
        'Gurdaspur': 'Semi-Arid',
        'Hoshiarpur': 'Semi-Arid',
        'Jalandhar': 'Semi-Arid',
        'Kapurthala': 'Semi-Arid',
        'Ludhiana': 'Semi-Arid',
        'Mansa': 'Semi-Arid',
        'Moga': 'Semi-Arid',
        'Muktsar': 'Semi-Arid',
        'Nawanshahr': 'Semi-Arid',
        'Pathankot': 'Semi-Arid',
        'Patiala': 'Semi-Arid',
        'Rupnagar': 'Semi-Arid',
        'Sangrur': 'Semi-Arid',
        'SAS Nagar': 'Semi-Arid',
        'Tarn Taran': 'Semi-Arid'
    },
    'Haryana': {
        'Ambala': 'Semi-Arid',
        'Bhiwani': 'Semi-Arid',
        'Charkhi Dadri': 'Semi-Arid',
        'Faridabad': 'Semi-Arid',
        'Fatehabad': 'Semi-Arid',
        'Gurugram': 'Semi-Arid',
        'Hisar': 'Semi-Arid',
        'Jhajjar': 'Semi-Arid',
        'Jind': 'Semi-Arid',
        'Kaithal': 'Semi-Arid',
        'Karnal': 'Semi-Arid',
        'Kurukshetra': 'Semi-Arid',
        'Mahendragarh': 'Semi-Arid',
        'Nuh': 'Semi-Arid',
        'Palwal': 'Semi-Arid',
        'Panchkula': 'Semi-Arid',
        'Panipat': 'Semi-Arid',
        'Rewari': 'Semi-Arid',
        'Rohtak': 'Semi-Arid',
        'Sirsa': 'Semi-Arid',
        'Sonipat': 'Semi-Arid',
        'Yamunanagar': 'Semi-Arid'
    },
    'Uttar Pradesh': {
        'Agra': 'Semi-Arid',
        'Aligarh': 'Semi-Arid',
        'Ambedkar Nagar': 'Tropical Wet and Dry',
        'Amethi': 'Tropical Wet and Dry',
        'Amroha': 'Semi-Arid',
        'Auraiya': 'Semi-Arid',
        'Azamgarh': 'Tropical Wet and Dry',
        'Baghpat': 'Semi-Arid',
        'Bahraich': 'Tropical Wet and Dry',
        'Ballia': 'Tropical Wet and Dry',
        'Balrampur': 'Tropical Wet and Dry',
        'Banda': 'Semi-Arid',
        'Barabanki': 'Tropical Wet and Dry',
        'Bareilly': 'Semi-Arid',
        'Basti': 'Tropical Wet and Dry',
        'Bhadohi': 'Tropical Wet and Dry',
        'Bijnor': 'Semi-Arid',
        'Budaun': 'Semi-Arid',
        'Bulandshahr': 'Semi-Arid',
        'Chandauli': 'Tropical Wet and Dry',
        'Chitrakoot': 'Semi-Arid',
        'Deoria': 'Tropical Wet and Dry',
        'Etah': 'Semi-Arid',
        'Etawah': 'Semi-Arid',
        'Ayodhya': 'Tropical Wet and Dry',
        'Farrukhabad': 'Semi-Arid',
        'Fatehpur': 'Semi-Arid',
        'Firozabad': 'Semi-Arid',
        'Gautam Buddha Nagar': 'Semi-Arid',
        'Ghaziabad': 'Semi-Arid',
        'Ghazipur': 'Tropical Wet and Dry',
        'Gonda': 'Tropical Wet and Dry',
        'Gorakhpur': 'Tropical Wet and Dry',
        'Hamirpur': 'Semi-Arid',
        'Hapur': 'Semi-Arid',
        'Hardoi': 'Tropical Wet and Dry',
        'Hathras': 'Semi-Arid',
        'Jalaun': 'Semi-Arid',
        'Jaunpur': 'Tropical Wet and Dry',
        'Jhansi': 'Semi-Arid',
        'Kannauj': 'Semi-Arid',
        'Kanpur Dehat': 'Semi-Arid',
        'Kanpur Nagar': 'Semi-Arid',
        'Kasganj': 'Semi-Arid',
        'Kaushambi': 'Tropical Wet and Dry',
        'Kushinagar': 'Tropical Wet and Dry',
        'Lakhimpur Kheri': 'Tropical Wet and Dry',
        'Lalitpur': 'Semi-Arid',
        'Lucknow': 'Tropical Wet and Dry',
        'Maharajganj': 'Tropical Wet and Dry',
        'Mahoba': 'Semi-Arid',
        'Mainpuri': 'Semi-Arid',
        'Mathura': 'Semi-Arid',
        'Mau': 'Tropical Wet and Dry',
        'Meerut': 'Semi-Arid',
        'Mirzapur': 'Tropical Wet and Dry',
        'Moradabad': 'Semi-Arid',
        'Muzaffarnagar': 'Semi-Arid',
        'Pilibhit': 'Semi-Arid',
        'Pratapgarh': 'Tropical Wet and Dry',
        'Prayagraj': 'Tropical Wet and Dry',
        'Rae Bareli': 'Tropical Wet and Dry',
        'Rampur': 'Semi-Arid',
        'Saharanpur': 'Semi-Arid',
        'Sambhal': 'Semi-Arid',
        'Sant Kabir Nagar': 'Tropical Wet and Dry',
        'Shahjahanpur': 'Semi-Arid',
        'Shamli': 'Semi-Arid',
        'Shravasti': 'Tropical Wet and Dry',
        'Siddharthnagar': 'Tropical Wet and Dry',
        'Sitapur': 'Tropical Wet and Dry',
        'Sonbhadra': 'Tropical Wet and Dry',
        'Sultanpur': 'Tropical Wet and Dry',
        'Unnao': 'Tropical Wet and Dry',
        'Varanasi': 'Tropical Wet and Dry'
    },
    'Rajasthan': {
        'Ajmer': 'Semi-Arid',
        'Alwar': 'Semi-Arid',
        'Banswara': 'Tropical Wet and Dry',
        'Baran': 'Tropical Wet and Dry',
        'Barmer': 'Semi-Arid',
        'Bharatpur': 'Semi-Arid',
        'Bhilwara': 'Semi-Arid',
        'Bikaner': 'Semi-Arid',
        'Bundi': 'Semi-Arid',
        'Chittorgarh': 'Semi-Arid',
        'Churu': 'Semi-Arid',
        'Dausa': 'Semi-Arid',
        'Dholpur': 'Semi-Arid',
        'Dungarpur': 'Tropical Wet and Dry',
        'Hanumangarh': 'Semi-Arid',
        'Jaipur': 'Semi-Arid',
        'Jaisalmer': 'Semi-Arid',
        'Jalore': 'Semi-Arid',
        'Jhalawar': 'Tropical Wet and Dry',
        'Jhunjhunu': 'Semi-Arid',
        'Jodhpur': 'Semi-Arid',
        'Karauli': 'Semi-Arid',
        'Kota': 'Semi-Arid',
        'Nagaur': 'Semi-Arid',
        'Pali': 'Semi-Arid',
        'Pratapgarh': 'Semi-Arid',
        'Rajsamand': 'Semi-Arid',
        'Sawai Madhopur': 'Semi-Arid',
        'Sikar': 'Semi-Arid',
        'Sirohi': 'Semi-Arid',
        'Sri Ganganagar': 'Semi-Arid',
        'Tonk': 'Semi-Arid',
        'Udaipur': 'Semi-Arid'
    },
    'Gujarat': {
        'Ahmedabad': 'Semi-Arid',
        'Amreli': 'Semi-Arid',
        'Anand': 'Semi-Arid',
        'Aravalli': 'Semi-Arid',
        'Banaskantha': 'Semi-Arid',
        'Bharuch': 'Tropical Wet and Dry',
        'Bhavnagar': 'Semi-Arid',
        'Botad': 'Semi-Arid',
        'Chhota Udaipur': 'Tropical Wet and Dry',
        'Dahod': 'Tropical Wet and Dry',
        'Dang': 'Tropical Wet',
        'Devbhoomi Dwarka': 'Tropical Wet',
        'Gandhinagar': 'Semi-Arid',
        'Gir Somnath': 'Tropical Wet and Dry',
        'Jamnagar': 'Semi-Arid',
        'Junagadh': 'Tropical Wet and Dry',
        'Kheda': 'Semi-Arid',
        'Kutch': 'Semi-Arid',
        'Mahisagar': 'Tropical Wet and Dry',
        'Mehsana': 'Semi-Arid',
        'Morbi': 'Semi-Arid',
        'Narmada': 'Tropical Wet and Dry',
        'Navsari': 'Tropical Wet',
        'Panchmahal': 'Tropical Wet and Dry',
        'Patan': 'Semi-Arid',
        'Porbandar': 'Tropical Wet',
        'Rajkot': 'Semi-Arid',
        'Sabarkantha': 'Semi-Arid',
        'Surat': 'Tropical Wet',
        'Surendranagar': 'Semi-Arid',
        'Tapi': 'Tropical Wet and Dry',
        'Vadodara': 'Tropical Wet and Dry',
        'Valsad': 'Tropical Wet'
    },
    'Tamil Nadu': {
        'Ariyalur': 'Tropical Wet and Dry',
        'Chennai': 'Tropical Wet',
        'Coimbatore': 'Tropical Wet and Dry',
        'Cuddalore': 'Tropical Wet',
        'Dharmapuri': 'Tropical Wet and Dry',
        'Dindigul': 'Tropical Wet and Dry',
        'Erode': 'Tropical Wet and Dry',
        'Kanchipuram': 'Tropical Wet',
        'Kanyakumari': 'Tropical Wet',
        'Karur': 'Tropical Wet and Dry',
        'Krishnagiri': 'Tropical Wet and Dry',
        'Madurai': 'Tropical Wet and Dry',
        'Nagapattinam': 'Tropical Wet',
        'Namakkal': 'Tropical Wet and Dry',
        'Nilgiris': 'Tropical Wet',
        'Perambalur': 'Tropical Wet and Dry',
        'Pudukkottai': 'Tropical Wet and Dry',
        'Ramanathapuram': 'Tropical Wet and Dry',
        'Salem': 'Tropical Wet and Dry',
        'Sivaganga': 'Tropical Wet and Dry',
        'Thanjavur': 'Tropical Wet',
        'Theni': 'Tropical Wet and Dry',
        'Thoothukudi': 'Tropical Wet',
        'Tiruchirappalli': 'Tropical Wet and Dry',
        'Tirunelveli': 'Tropical Wet and Dry',
        'Tiruppur': 'Tropical Wet and Dry',
        'Tiruvallur': 'Tropical Wet',
        'Tiruvannamalai': 'Tropical Wet and Dry',
        'Tiruvarur': 'Tropical Wet',
        'Vellore': 'Tropical Wet and Dry',
        'Viluppuram': 'Tropical Wet',
        'Virudhunagar': 'Tropical Wet and Dry'
    },
    'Kerala': {
        'Alappuzha': 'Tropical Wet',
        'Ernakulam': 'Tropical Wet',
        'Idukki': 'Tropical Wet',
        'Kannur': 'Tropical Wet',
        'Kasaragod': 'Tropical Wet',
        'Kollam': 'Tropical Wet',
        'Kottayam': 'Tropical Wet',
        'Kozhikode': 'Tropical Wet',
        'Malappuram': 'Tropical Wet',
        'Palakkad': 'Tropical Wet',
        'Pathanamthitta': 'Tropical Wet',
        'Thiruvananthapuram': 'Tropical Wet',
        'Thrissur': 'Tropical Wet',
        'Wayanad': 'Tropical Wet'
    }
}

CROP_SUITABILITY = {
    'Red Sandy Loam': {
        'Semi-Arid': ['Groundnut', 'Sunflower', 'Sorghum', 'Pearl Millet', 'Pigeon Pea', 'Vegetables'],
        'Tropical Wet': ['Groundnut', 'Sunflower', 'Maize', 'Soybean', 'Pigeon Pea', 'Vegetables'],
        'Tropical Wet and Dry': ['Groundnut', 'Sunflower', 'Maize', 'Soybean', 'Pigeon Pea', 'Vegetables']
    },
    'Black Cotton': {
        'Semi-Arid': ['Cotton', 'Sorghum', 'Pearl Millet', 'Pigeon Pea', 'Vegetables'],
        'Tropical Wet': ['Cotton', 'Maize', 'Soybean', 'Pigeon Pea', 'Vegetables'],
        'Tropical Wet and Dry': ['Cotton', 'Maize', 'Soybean', 'Pigeon Pea', 'Vegetables']
    },
    'Red Loam': {
        'Semi-Arid': ['Groundnut', 'Sunflower', 'Sorghum', 'Pearl Millet', 'Vegetables'],
        'Tropical Wet': ['Rice', 'Maize', 'Soybean', 'Vegetables', 'Fruits'],
        'Tropical Wet and Dry': ['Groundnut', 'Sunflower', 'Maize', 'Soybean', 'Vegetables']
    },
    'Alluvial': {
        'Semi-Arid': ['Wheat', 'Barley', 'Mustard', 'Chickpea', 'Vegetables'],
        'Tropical Wet': ['Rice', 'Sugarcane', 'Vegetables', 'Fruits'],
        'Tropical Wet and Dry': ['Rice', 'Wheat', 'Sugarcane', 'Vegetables']
    },
    'Laterite': {
        'Semi-Arid': ['Cashew', 'Coconut', 'Arecanut', 'Coffee', 'Vegetables'],
        'Tropical Wet': ['Cashew', 'Coconut', 'Arecanut', 'Coffee', 'Tea', 'Vegetables'],
        'Tropical Wet and Dry': ['Cashew', 'Coconut', 'Arecanut', 'Coffee', 'Vegetables']
    },
    'Coastal Alluvial': {
        'Semi-Arid': ['Rice', 'Vegetables', 'Coconut'],
        'Tropical Wet': ['Rice', 'Coconut', 'Cashew', 'Vegetables'],
        'Tropical Wet and Dry': ['Rice', 'Coconut', 'Cashew', 'Vegetables']
    }
}

MARKET_DEMAND = {
    'Rice': {'demand': 'High', 'price_trend': 'Stable', 'export_potential': 'High'},
    'Wheat': {'demand': 'High', 'price_trend': 'Stable', 'export_potential': 'Medium'},
    'Maize': {'demand': 'High', 'price_trend': 'Increasing', 'export_potential': 'High'},
    'Cotton': {'demand': 'High', 'price_trend': 'Stable', 'export_potential': 'High'},
    'Sugarcane': {'demand': 'High', 'price_trend': 'Stable', 'export_potential': 'Medium'},
    'Groundnut': {'demand': 'Medium', 'price_trend': 'Increasing', 'export_potential': 'High'},
    'Sunflower': {'demand': 'Medium', 'price_trend': 'Stable', 'export_potential': 'Medium'},
    'Soybean': {'demand': 'High', 'price_trend': 'Increasing', 'export_potential': 'High'},
    'Vegetables': {'demand': 'High', 'price_trend': 'Stable', 'export_potential': 'Medium'},
    'Fruits': {'demand': 'High', 'price_trend': 'Stable', 'export_potential': 'High'},
    'Coffee': {'demand': 'High', 'price_trend': 'Increasing', 'export_potential': 'High'},
    'Tea': {'demand': 'High', 'price_trend': 'Stable', 'export_potential': 'High'},
    'Cashew': {'demand': 'High', 'price_trend': 'Increasing', 'export_potential': 'High'},
    'Coconut': {'demand': 'High', 'price_trend': 'Stable', 'export_potential': 'Medium'},
    'Arecanut': {'demand': 'Medium', 'price_trend': 'Stable', 'export_potential': 'Medium'}
}

GOVERNMENT_SCHEMES = {
    'PM-KISAN': {
        'description': 'Income support of ₹6000 per year to all farmer families',
        'eligibility': 'All farmer families',
        'benefits': '₹6000 per year in three equal installments'
    },
    'PMFBY': {
        'description': 'Crop insurance scheme',
        'eligibility': 'All farmers including sharecroppers and tenant farmers',
        'benefits': 'Comprehensive crop insurance against natural calamities'
    },
    'Soil Health Card': {
        'description': 'Soil health assessment and recommendations',
        'eligibility': 'All farmers',
        'benefits': 'Free soil testing and recommendations'
    },
    'Micro Irrigation': {
        'description': 'Drip and sprinkler irrigation systems',
        'eligibility': 'All farmers',
        'benefits': 'Subsidy up to 55% for small and marginal farmers'
    }
}

SEASONAL_CALENDAR = {
    'Kharif': {
        'months': ['June', 'July', 'August', 'September', 'October'],
        'crops': ['Rice', 'Maize', 'Cotton', 'Soybean', 'Groundnut', 'Sunflower']
    },
    'Rabi': {
        'months': ['October', 'November', 'December', 'January', 'February', 'March'],
        'crops': ['Wheat', 'Barley', 'Mustard', 'Chickpea', 'Peas']
    },
    'Zaid': {
        'months': ['March', 'April', 'May', 'June'],
        'crops': ['Vegetables', 'Watermelon', 'Cucumber', 'Pumpkin']
    }
} 